In [8]:
with open('cleaned.txt', 'r') as file:
    lines = file.readlines()

In [9]:
dhivehi_parts = []
english_parts = []

for line in lines:
    eng_part = line.split(',')[-1].split('|')[0].strip()
    dv_part = line.split('|')[-1].strip()

    dhivehi_parts.append(dv_part)
    english_parts.append(eng_part)

In [11]:
import pandas as pd

df = pd.DataFrame({
    'latin': english_parts,
    'dhivehi': dhivehi_parts,
})
df.to_csv('training_data.csv', index=False)

In [12]:
df = pd.read_csv('training_data.csv')
df

,latin,dhivehi
0,Abdulrahman ge anhenunge phone fuluhun hifahat...,އަބްދުއްރަހުމާންގެ އަންހެނުންގެ ފޯނު ފުލުހުން ...
1,Vinares tower in vettunu zuvaanaa niyaa vejje,ވިނަރެސް ޓަވަރުން ވެއްޓުނު ޒުވާނާ ނިޔާވެއްޖެ
2,Vinares ge Tower akah vetti meehakah aniyaa vejje,ވިނަރެސްގެ ޓަވަރަކުން ވެއްޓި މީހަކަށް އަނިޔާވެ...
3,King charles aai Raees Muizzu bahdhalu kuravvaifi,ރަސްގެފާނު ޗާލްސް އާއި ރައީސް މުއިއްޒު ބައްދަލ...
4,Kuli nudhakkaa nama loan libun dhathivaa goiy ...,އެޗްޑީސީގެ ފްލެޓުތަކަށް ކުލި ނުދައްކާ ނަމަ ލޯނ...
...,...,...
19974,Kamadhoo council in Raees ah dhinee A report eh,"ކަމަދޫ ކައުންސިލުން ރައީސަށް ދިނީ ""އޭ ރިޕޯޓު"""
19975,MDP ge campaign jalsa akah City councilun hudh...,އެމްޑީޕީގެ ކެމްޕެއިން ޖަލްސާއަކަށް ސިޓީ ކައުން...
19976,ekamaku dhoo nudheythi: Raees,މި ވެރިކަން ބަދަލުކުރުމުގެ މާ ޖޯޝެއް ނެތް، އެކ...
19977,vaudhu thah akurun akurah fudhdhaane: Raees,ރަށްރަށަށް ކަމެއް ކޮށްދޭނީ މި ސަރުކާރުން، ވައު...
19978,Ithurah campaign varugadha kuran beununvey,އައްޑޫގެ ތާއީދާ މެދު މުއިއްޒު ހިތްހަމަޖެހޭ، އި...